### ISSUE TITLE
Will the new PS4 Eye Camera be supported?

### ISSUE THREAD

**Issue by nlpguyz** [ps4eye/ps4eye#11]
With the new model that looks the one below, after updating the firmware, the video device node doesn't appear. The vid:pid is updated as expected.

![image](https://user-images.githubusercontent.com/25698072/60925347-40d47d00-a258-11e9-9595-6d54d571b59f.png)

Any idea?

**Comment by nlpguyz** [comment]
After running ps4eye_init.py to update the firmware, I did run "sudo python ps4eye_cmd.py startup.bin". The log showed the error below:

setupTxn: 40 A4 0000 0000 0024 (36)
setupTxn: 40 A4 0000 0000 000C (12)
PS4 camera commands done
device 0:
endpoint 0 : 81
aborting camera read
attaching kernel driver...
Traceback (most recent call last):
  File "ps4eye_cmd.py", line 104, in <module>
    dev.attach_kernel_driver(0)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 1089, in attach_kernel_driver
    interface)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 906, in attach_kernel_driver
    _check(self.lib.libusb_attach_kernel_driver(dev_handle.handle, intf))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 2] Entity not found

**Comment by AlbeyAmakiir** [comment]
I am having this issue, too. Doesn't seem like this repo has been touched in years, though, so unless someone else has worked on it, I suspect the solution is to get an older one.
