### ISSUE TITLE
ps4eye_cmd.py is not compatible with python 3

### ISSUE THREAD

**Issue by sl1pkn07** [ps4eye/ps4eye#14]
~~~
└───╼  ./ps4eye_cmd.py startup.bin 
  File "/media/COSAS/aplicaciones/ps4eye/python/./ps4eye_cmd.py", line 13
    print 'PS4 camera not initialized'
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
~~~

after pass the program 2to3 program, i get 

~~~
└───╼  ./ps4eye_cmd.py startup.bin 
PS4 camera command file startup.bin opened
Traceback (most recent call last):
  File "/media/COSAS/aplicaciones/ps4eye/python/./ps4eye_cmd.py", line 30, in <module>
    wtype     = ord(setup[0])
TypeError: ord() expected string of length 1, but int found
~~~

any repo with this fixed?

greetings

**Comment by sl1pkn07** [comment]
this also affect to the other scripts
